### ISSUE TITLE
`nix` in public API

### ISSUE THREAD

**Issue by MaxVerevkin** [KillingSpark/rustbus#100]
I think it is better not to expose `nix` types in the public API, such as `RecvConn::can_read_from_source`.

1. `nix` is an implementation detail.
2. Currently updating `nix` to a new incompatible version requires a new incompatible release of `rustbus`.

**Comment by KillingSpark** [comment]
I agree, the library should not leak types of any dependency

**Comment by KillingSpark** [comment]
to be honest i am surprised clippy doesn't contain a lint for that, it seems like an obvious anti-pattern

**Comment by MaxVerevkin** [comment]
> to be honest i am surprised clippy doesn't contain a lint for that, it seems like an obvious anti-pattern

Apparently there is work being done in this direction: https://rust-lang.github.io/rfcs/3516-public-private-dependencies.html

**Comment by KillingSpark** [comment]
Oh that's nice!
