### ISSUE TITLE
Make the Marshal trait object-safe

### ISSUE THREAD

**Issue by cmaves** [KillingSpark/rustbus#26]
I think it would make the ergonomics of the Marshal better if it you could construct `Box<dyn Marshal>`. `Box<dyn Marshal>` corresponds well to D-Bus's variant, and is a pattern that users of this crate would likely come across very well.

In order to this the `signature` and `alignment` methods need to be given a receiver as a parameter (like `&self`). I don't think this would change would be very restrictive because in most cases users who need to access the `signature` or `alignment` methods will already have an instance of the implementing object.

**Comment by cmaves** [comment]
After looking at this a bit more, I realize that this change is a bit more difficult than I initially thought because the `signature` and `alignment` methods have been moved into their own unreleased Super trait which is used by `Unmarshal`. And the new impls for `Unmarshal` often use the associated methods in a way that is hard to get away from.

**Comment by KillingSpark** [comment]
The first try to implement this was object-safe. The issue here is: how do you determin the signature for an empty collection? The impl of Signature for Vec<E> or Hashmap<K,V> does not work with object-safe traits. At least I couldnt find a way, maybe I am missing something?

I totally agree that it would be nicer to have the possibility of a &dyn Marshal, but I don't see how it can be done.

**Comment by KillingSpark** [comment]
I thought that it might be possible with some weird hacks around Any and TypeId but I think that would require user-defined types to somehow register with the library. I think the complications of getting this to work are not really worth it.

**Comment by cmaves** [comment]
I was trying to implement it myself and ran into the same problem `Vec<E>`. The only solution I could think of was having two functions in the trait that are identical but that seems messy to me.

One final question about the `Marshal` trait. Is the `alignment()` function necessary (or could it be a provided method)? Is there any case where the value returned by `alignment()` would differ from `signature::Type::get_alignment()` on the `Type` returned by the `signature()`.

**Comment by cmaves** [comment]
Ah, It appears like it is a performance optimization. If `Type` contains a `Vec` then the call to `Self::signature().get_alignment` would not get inlined. It does seem like it could be a provided method and implementors could override it if they chose to but that is nitpicking.

**Comment by KillingSpark** [comment]
Also making the signature for vec/struct would allocate a vector, which would be very bad in a tight marshalling loop.

Always glad to have a second person agreeing. I was a bit worried I had overlooked a cool feature that would allow this to work.
