### ISSUE TITLE
Variant generation macro

### ISSUE THREAD

**Issue by KillingSpark** [KillingSpark/rustbus#35]
It is currently annoying to make Variants work with the trait based API. A macro that generates the boilerplate code to marshal/unmarshal the enum that represents the Variant would be very helpful. Different approaches have already been discussed in the PR #32 . The development is happening on the branch [variant_trait_impl](https://github.com/KillingSpark/rustbus/tree/variant_trait_impl).

In general the macro should work something like this: 
```dbus_variant!(Name; Option1Name => TypeName1; Option2Name => TypeName2; ...);```
And generate an enum like this:
```rust
pub enum Name {
    Option1Name(TypeName1),
    Option2Name(TypeName2),
    Catchall(SOMETHING),
}
```
It also generates the appropriate marshalling and unmarshalling for all the cases.

The `Catchall` case is needed when unmarshalling a message that does not fit any of the given cases. There are some options what can be in there:
1. Just drop/skip the variant, and Catchall just signals "Hey you missed some data here"
1. Just drop/skip the variant but remember the Signature
1. Use the Variant struct provided by [cmaves](https://github.com/cmaves) in #32 to provide access to the content dynamically
1. Use rustbus::Param to provide access to the content dynamically

**Comment by KillingSpark** [comment]
Both the Variant from #32 and rustbus::Param introduce lifetimes to the type of the produced enum which proves to be very annoying in the macro.

**Comment by cmaves** [comment]
Is introducing the lifetimes annoying because of implementation issues or something else?

I think lifetimes should be added to the enum (regardless of what option is used above) to add support reference types in the generated enum or types that have a lifetime parameter. This could be a useful addition.

**Comment by cmaves** [comment]
To expand on how I would use lifetimes, the enum would have the `'buf` lifetime that could be used in the macro call.
I envision something along these lines that allows for `&'buf str` or `&'buf [u8]`:
```rust
dbus_variant!(TestVar, Str => &'buf str);
/* Generates
pub enum TestVar<'buf>{
    Str(&'buf str),
    Catchall(Variant<'buf>) // or the Param<'buf>
}
*/

fn main() {
	let mut body = rustbus::message_builder::MarshalledMessageBody::new();
	body.push_variant("Hello World!").unwrap();
	body.push_variant(100_i32).unwrap();
	let mut parser = body.parser();
	eprintln!("{:?}", body);
	let var: TestVar = parser.get().unwrap();
	match var {
		TestVar::Str(s) => println!("Unmarshaled str: {}", s),
		TestVar::Catchall(_) => unreachable!()
	}
	eprintln!("{:?}", parser);
	let var: TestVar = parser.get().unwrap();
	match var {
		TestVar::Catchall(i) => println!("Unmarshaled i32: {}", i.get::<i32>().unwrap()),
		TestVar::Str(_) => unreachable!()
	}
}
```

Here is the blob with my quick changes that make this work: [src/wire/mod.rs](https://github.com/cmaves/rustbus/blob/rustable_dev/src/wire/mod.rs)  /  [src/wire/unmarshal/traits.rs](https://github.com/cmaves/rustbus/blob/rustable_dev/src/wire/unmarshal/traits.rs). 

These changes are untested beyond the above code example.

**Comment by KillingSpark** [comment]
I totally agree that they should exist in most cases. But this does not work for the case where:

1. All cases do not have a &'buf reference
2. The catchall should contain the signature not the variant

This would result in a compiler error, because 'buf is not used. And even if a PhantomData<'buf> would be used, it would limit the ergonomics because the variant would be needlessly bound to the lifetime of the message.

It might be necessary to make this two macros, one that allows the completely owned stuff and one that allows for &'buf references used.

Maybe this is actually too complex for normal macros and should just be done with proc-macros but I am totally unfamiliar with those too :/

**Comment by cmaves** [comment]
Yeah, I wrote that code with the assumption  `Variant` would be used. I think just having two types is best. One that use a catchall without a reference type (`Signature`) and disallow reference variant types on it. And another with a catchall with a reference type that allows additional reference type variants (like `&str`). People can just pick which one they want based on their needs.

**Comment by KillingSpark** [comment]
So I got around to implementing this in 0a8546f397014852a81ad24dea4ae015332d86e5. I think what would help me a lot would be an actual client or server using rustbus (in a more complex way than the existing examples) to see how well / bad all of the stuff in this library actually works. Do you use rustbus in that way? If not I'll probably focus on that for a bit.

**Comment by KillingSpark** [comment]
I merged the variant_trait_impl branch into master. I will make another round of cleanup and make a new release soon.

**Comment by cmaves** [comment]
I use rustbus extensively to implement my Bluez crate [`rustable`](https://github.com/cmaves/rustable).
For this issue specifically, I plan to use the Variant macro to implement the `org.freedesktop.DBus.Properties` API. You can look at my current implementation [here](https://github.com/cmaves/rustable/blob/eb74fa97ad46fd0500ee39922119660b5564ca91/src/lib.rs#L1646), which use the old `Params` enum for this task.

**Comment by KillingSpark** [comment]
This is good to know! I like to develop towards real needs :)
