### ISSUE TITLE
multithreading and rustbus::Conn

### ISSUE THREAD

**Issue by okeri** [KillingSpark/rustbus#4]
Hello, first for all, thank you for this project. I have found rustbus code very well readable. I guess it's standard situation, when dbus interface designed with both methods and signals and signals dispatches from separate threads independent of thread listens for incoming method calls. So i want to ask you about the most idiomatic way to implement this approarch using rustbus. In my situation it's enough for me to listen incoming calls in on thread, and emit signals from another threads. As far as i know, POSIX systems allows this approach without any additional synchronization. So it seams the easiest way for me is just share stream and serial_counter members from Conn struct by implementing Clone trait.
And ofc i could do it by myself and contribute pull request .. BUT this solution will also allow  multithreading reads. However using multiple blocking reads of the same socket from different threads is not really desirable solution. So what do you think ?

**Comment by KillingSpark** [comment]
I think you shouldn't use a dbus connection from multiple threads at all. It would probably be better to use channels and have one thread read from those and emit signals as needed and write to the channels when calls come in

**Comment by okeri** [comment]
In this case signals have to be synced to method calls... just because of "dbus thread" blocked by read from socket and cannot read from channels at the same time (i guess we are talking about mpsc)
anyway, thank you for your answer.
