### ISSUE TITLE
Using the Connections for sending signals while also waiting for messages is impossible

### ISSUE THREAD

**Issue by KillingSpark** [KillingSpark/rustbus#45]
If you want to write a service that wants to both
1. Wait for messages to respond to them
2. Send signals about external events, unrelated to these calls

then the current connections are a bad fit for that. Imagine for example a filesystem watcher, that sends some inotify events as signals over dbus.

Since these requirements most likely mean that your service is multithreaded a threadsafe alternative to `connection::Conn` could be the solution here. It would need a mechanism to queue up for writing to the socket. Just sharing the UnixStream is not feasible since sending a message might involve multiple consecutive writes.

I see two possible solutions here: 
1. Queue the messages, this could lead to unexpected amounts of memory being used if a lot of messages are queued at once
1. Actually make the threads wait for the socket to be free and then send the message synchronously, depending on what your are doing this could harm the effectiveness of multithreading your service in the first place

It might even be necessary to make both of those possible. Mixing the approaches is also possible.

**Comment by cmaves** [comment]
I've have run into this exact issue before. This is the problem my `AsRawFd` PR was intended to help resolve.
For example if you are writing a filesystem watcher with Linux's inotify interface, you can poll both the `Conn` fd and inotify fd. If the `Conn` has data try refilling with `refill_all` then handle any potential messages (or incoming signals). If inotify fd has data, read it and handle it, by possibly sending signals. You don't necessarily need signals.
It isn't the cleanest workaround but it avoids having to make `RpcConn` thread-safe, and the associated performance penalty.

**Comment by KillingSpark** [comment]
Yeah, I have some more thoughts about this, like splitting the connections into two separate structs one for reading and one for sending, to make the sharing of the sending part easier / decoupled from the receiving part. I'll have to think this through more thoroughly. If I come up with anything I'll update this issue.

I see how the RawFd approach works in your case, but if you are listening for events that are not coming from another FD it might get even hairier, so a more general solution to this would be beneficial.

**Comment by cmaves** [comment]
I'm not sure that splitting the connections is a particular useful thing to do. If you are receiving messages, you almost certainly have to send messages in the same part of your program, because you have to respond to invalid messages and filtered messages (like those returned by `refill_all` method. Plus you still have the issue of lock contention, which can negate the effects of a true multi-threaded `Conn`. I would instead focus on making the `Conn` and `RpcConn` `Send` structs so that they can be stored behind a `Mutex` and accessed from different threads.

This issue exists with any kind of program that has a socket-based interface. You often just have to design your program around it and avoid blocking calls.

**Comment by cmaves** [comment]
On a unrelated note,  @KillingSpark can you bump the version? PR #43 fixes a breaking bug that prevented `Container::Dict` from being unmarshalled. It would be nice to get that fix in a release before merging a bunch of stuff from dispatch_conn branch (that could include breaking changes.)

**Comment by KillingSpark** [comment]
>On a unrelated note, @KillingSpark can you bump the version? PR #43 fixes a breaking bug that prevented Container::Dict from being unmarshalled. It would be nice to get that fix in a release before merging a bunch of stuff from dispatch_conn branch (that could include breaking changes.)

Sure! I tend to forget to do that, please feel free to poke me on stuff like this. There is a new github v0.9.1 release and it's up on crates.io as 0.9.1.

**Comment by KillingSpark** [comment]
>I'm not sure that splitting the connections is a particular useful thing to do. If you are receiving messages, you almost certainly have to send messages in the same part of your program, because you have to respond to invalid messages and filtered messages (like those returned by refill_all method. Plus you still have the issue of lock contention, which can negate the effects of a true multi-threaded Conn. I would instead focus on making the Conn and RpcConn Send structs so that they can be stored behind a Mutex and accessed from different threads.

> This issue exists with any kind of program that has a socket-based interface. You often just have to design your program around it and avoid blocking calls.

I think splitting the low level `Conn` would allow for more freedom of choice on the abstractions built over it. The current RpcConn would not have to changed in any way visible externally (it would just have two members one for writing and one for reading messages).

This issue is more or less meant as a reminder to think about this in the future. Currently I want to finish the dispatch_conn stuff first and then decide which of the few issues I created to tackle first :)

**Comment by KillingSpark** [comment]
I am tackling this in the branch `split_conn`. Currently I only did this for the DispatchConn as that seems to be the main usecase here. Switching the RpcConn to use a `Arc<Mutex<SendConn>>` would be trivial though. Using an `Arc<Mutex<>>` should not be a big performance concern compared to the kernel context switches involved in send_message().

**Comment by KillingSpark** [comment]
This has been merged into master. 

The low level Conn has been split into a DuplexConn which has a SendConn and a RecvConn that can be used completely separately.

DispatchConn now provides the possibility to have multiple references to the SendConn through the `Arc<Mutex<SendConn>>`. 

I think I will close this issue for now, as it is not technically impossible anymore to send signals while waiting for more messages. If there are more specific issues around this topic please feel free to open a new issue :)
