### ISSUE TITLE
Please release a new rustbus crate

### ISSUE THREAD

**Issue by davide125** [KillingSpark/rustbus#69]
I'm trying to package rustbus in Fedora, but the latest published crate (0.12.0) depends on rustbus_derive 0.1.2 which depends itself on rustbus 0.11.0, creating an unresolvable circular dependency. I see this seems to already be fixed in rustbus_derive 0.2.0, but the corresponding rustbus crate isn't published. Thanks!

**Comment by KillingSpark** [comment]
Yeah that circular dependency was not good. I have merged some PRs from cmaves today so I'll bump the version once again and then I'll publish a new release. I'll get on that soon.

Out of interest, what benefit does it have to package rustbus for fedora? Does fedora have a concept of source packages? I'm not familiar with the distro.

**Comment by davide125** [comment]
Thanks!

Yes, Fedora ships source packages for Rust: https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/. I'm working to package https://github.com/facebookexperimental/resctl-demo and rustbus is one of its dependencies.

**Comment by KillingSpark** [comment]
Sorry for the delay, I hope I'll be faster again in the future. I'm currently a bit busy with my personal life. As soon as the last minor thing in #68 is resolved I'll make the new release!

**Comment by KillingSpark** [comment]
version 0.14.0 has been published on crates.io. I hope this solves your difficulties :)

**Comment by davide125** [comment]
Hit a few minor issues (#71, #72, #73) but got the crate to build in the end, so I think we can close this. The Fedora package review is up at https://bugzilla.redhat.com/show_bug.cgi?id=1979716 

Thanks again for your help!

**Comment by KillingSpark** [comment]
I am always glad to help! Also exiting to see that there is continued interest in this crate.
