### ISSUE TITLE
MarshalledMessageBody::push_param[2-5] should atomically fail

### ISSUE THREAD

**Issue by cmaves** [KillingSpark/rustbus#70]
Currently if `push_param2-5` methods fail midway through marshalling, the previously successful parameters will remain in the message body. IMO, the fail behavior should revert the previously marshalled parameters if any fails. Otherwise error handling is difficult to write and kinda of makes the push_param[2-5] functions too difficult to use.

**Comment by cmaves** [comment]
This strikes me as a low priority issue, but something to consider fixing in the future

**Comment by KillingSpark** [comment]
You mean handling it similarly to get[2-5] on MessageBodyParser uses a helper function that reverts the state if an error occurred in any of the calls? Seems like a good idea! :+1:

**Comment by KillingSpark** [comment]
This has been implemented with 297bc3b54c12ae303651dc0da84d9ac07e7b8b73 . This will make it into the next release :)

**Comment by cmaves** [comment]
Well this looks good!!
