### ISSUE TITLE
Add a way to get the file descriptors for use with epoll

### ISSUE THREAD

**Issue by i509VCB** [KillingSpark/rustbus#77]
At the moment I don't see a way to take DuplexConn or the higher level RpcConn and get the file descriptor(s) that I can use in epoll for not blocking or needing to poll like crazy.

**Comment by cmaves** [comment]
`AsRawFd` is implemented for `DuplexConn` which gives the receiving `RawFd`. If your using `RpcConn`, you can use `RpcConn::conn()` to get the underlying `DuplexConn` first.
