### ISSUE TITLE
Cut new version on crates.io

### ISSUE THREAD

**Issue by l1na-forever** [KillingSpark/rustbus#78]
Hi! I'm using rustbus [in a small project](https://github.com/l1na-forever/mpris-notifier) - thanks for the crate! - where I've made use of a few of the nice changes waiting on `master` (the error cleanup and enum derive macros). However, because those aren't yet in a release published to crates.io, I'm blocked from publishing my own crate (unless I revert to a previous version, which I'd rather avoid). Given the last commit was in 2021, I was wondering if there are plans to release another version of `rustbus` with these changes?
Thanks!
Lina

**Comment by KillingSpark** [comment]
I don't even know why I didn't do that. While I am at it I'll update the dependencies, make sure everything looks good and make the release. 

Shouldn't take too long. If I keep you hanging don't be afraid to poke me

**Comment by l1na-forever** [comment]
Wow, thank you so much! :+1: :100: very much appreciated! I'll update my crate to match.
