### ISSUE TITLE
[help] can not get rustbus working, but dbus crate  and qbus cli does work

### ISSUE THREAD

**Issue by LuckyTurtleDev** [KillingSpark/rustbus#79]
I have try to execute the KDE plasmashell with this carte.
But I can not get it working.
I have try among others the following:
```rust
fn plasmashell(command: &str) -> Result<String, connection::Error> {
	let session_path = rustbus::get_session_bus_path()?;
	let mut con = DuplexConn::connect_to_bus(session_path, true)?;
	
	let mut sig = rustbus::MessageBuilder::new()
		.signal("org.kde.PlasmaShell", "evaluateScript", "/PlasmaShell")
		.build();
	sig.body.push_param(command).unwrap();
	sig.dynheader.destination = Some("org.kde.plasmashell".to_owned());
	con.send.send_message(&sig)?.write_all().map_err(force_finish_on_error)?;
	let message = con.recv.get_next_message(Timeout::Duration(Duration::from_millis(5000)))?;
	Ok(message.body.parser().get::<&str>().unwrap().to_owned())
```
But I did get a timeout:
```
ERROR: Dbus error: Timeout occured
```
With the qdbus cli it does work fine:
```bash
qdbus "org.kde.plasmashell" "/PlasmaShell" "org.kde.PlasmaShell.evaluateScript" "print(JSON.stringify(desktops()));"
```
It does also work with the dbus crate.
```rust
fn plasmashell(command: &str) -> Result<String, dbus::Error> {
	let destination = "org.kde.plasmashell";
	let interface = "org.kde.PlasmaShell";
	let path = "/PlasmaShell";
	let method = "evaluateScript";
	let args = (command,);
	let timeout = Duration::from_millis(5000);
	let conn = Connection::new_session()?;
	let proxy = conn.with_proxy(destination, path, timeout);
	let (ret,): (String,) = proxy.method_call(interface, method, args)?;
	Ok(ret)
}
```
QDBusViewer:
![image](https://user-images.githubusercontent.com/44570204/201200250-5cc74dbb-f89e-4f89-9698-c62d1ee367fe.png)

I do not know, what I can try, to get this working anymore.

**Comment by KillingSpark** [comment]
Soo I didn't do a deep dive yet, but what I noticed is that you use a signal with rustbus and a method call with the dbus crate. I'd guess the qdbus utility also does a method call by default? And in the screenshot of QDBusViewer it seems what you are trying to call is a method.
```
let mut sig = rustbus::MessageBuilder::new()
		.signal("org.kde.PlasmaShell", "evaluateScript", "/PlasmaShell")
		.build();
```
vs 
```
let (ret,): (String,) = proxy.method_call(interface, method, args)?;
```

So what you probably want is something like this:
```
let mut call = rustbus::MessageBuilder::new()
		.call("evaluateScript")
                .with_interface("org.kde.PlasmaShell")
                .on("/PlasmaShell")
		.build();
```

**Comment by KillingSpark** [comment]
So... I can reproduce this on my desktop. I'll try and find what the error is. For some reason the code reads 0 bytes from the socket even though data seems to be available. Very strange.

I'll get get back to you once I have more info :)

**Comment by KillingSpark** [comment]
Okay so what's going on is: Dbus requires you to send a special hello message before anything else. I forgot about that.

DuplexCon::send_hello does that for you.

You probably don't want to use DuplexCon though but rather the RpcConn which deals with the whole "match answer to call" stuff:

```rust
#[test]
fn plasmashell() {
    let session_path = crate::get_session_bus_path().expect("Wanna get session bus path :(");
    let mut con =
        RpcConn::connect_to_path(session_path, Timeout::Duration(Duration::from_millis(5000)))
            .expect("Wanna connect to bus :(");
            
    let mut call = crate::MessageBuilder::new()
        .call("evaluateScript")
        .with_interface("org.kde.PlasmaShell")
        .on("/PlasmaShell")
        .at("org.kde.plasmashell")
        .build();
    call.body
        .push_param("print(JSON.stringify(desktops()));")
        .unwrap();
    println!("Send call: {:?}", call);
    
    let id = con
        .send_message(&mut call)
        .expect("Wanna send message :(")
        .write_all()
        .map_err(force_finish_on_error)
        .expect("Wanna send message :(");
    let message = con
        .wait_response(id, Timeout::Duration(Duration::from_millis(5000)))
        .expect("Get failed");
    println!(
        "{}",
        message.body.parser().get::<&str>().unwrap().to_owned()
    )
}
```

**Comment by LuckyTurtleDev** [comment]
Thank you very much. This does work.

> Dbus requires you to send a special hello message before anything else

I did not know that this is a hard requirement, the other crates seem to do this automatic.

> You probably don't want to use DuplexCon though but rather the RpcConn which deals with the whole "match answer to call" stuff

I maybe focused too much at DuplexCon, because their was only a DuplexCon example at the readme.
But looks like the example at the doc is different and has also a RpcConn example.

**Comment by KillingSpark** [comment]
Glad this worked!

I'll reopen this just as a reminder for me because two todos arise from this:

* [ ] Detect reads of size 0 and report an error instead of blocking possibly until infinity if the other side closes the connection
* [ ] Update readme to highlight the RPCConn more, i.e. change the example to use the RPCConn strongly and only mention the DuplexCon in text.
