### ISSUE TITLE
Signature incorrectly parsed.

### ISSUE THREAD

**Issue by mehmooda** [KillingSpark/rustbus#82]
```rust
let mut sig_string = String::new();
rustbus::signature::Type::parse_description("aa{ss}").unwrap()[0].to_str(&mut sig_string);
assert_eq!(sig_string, "aa{ss}");
```

This currently makes it hard to roundtrip array of dicts; The following fails with wrong signature

```rust
    let mut msg = rustbus::message_builder::MarshalledMessageBody::new();
    msg.push_variant(&Vec::<HashMap::<String, String>>::new()).unwrap();
    msg.parser().get::<Vec::<HashMap::<String, String>>>().unwrap();
```

**Comment by KillingSpark** [comment]
Can confirm something about parsing this signature is broken, but only if dicts are involved. "aaas" is parsed correctly as `[[[string]]]`

I will investigate this further soon

**Comment by KillingSpark** [comment]
Interestingly there are two things at play here:

1. There is actually a bug in the parsing of the signatures, which I will publish a fix for soon
2. There is a bug in your code, that is not how variants work unfortunatly

```rust
        let original: Vec<std::collections::HashMap<u32, u32>> =
            vec![std::collections::HashMap::from_iter([(1, 1), (2, 2)])];
        let mut msg = crate::message_builder::MarshalledMessageBody::new();
        msg.push_variant(&original).unwrap();
        let mut parser = msg.parser();
        let variant = parser.get::<Variant>().unwrap();    // <---- first get the variant
        let v = variant
            .get::<Vec<std::collections::HashMap<u32, u32>>>()    // <---- then get the value out of the variant
            .unwrap();
        assert_eq!(original, v);
```

I know variants do not have the best discoverability in this library. I'll think about how this can be made more user friendly. 

* Either `get()` could check if the next value is a variant and do "the right thing" but I'll have to think about whether this has any edge cases that would break if I do this.
* Or I could introduce a `get_variant()` that works similarly to `get()` which essentially wraps the `get::<Variant>()?.get::<MyType>()`

**Comment by KillingSpark** [comment]
I hope version 0.19.2 fixes this issue :)

**Comment by mehmooda** [comment]
You're right. I was actually using an Variant Parser I made my self which owns the buffer. And allows the variant to be re-marshalled out:
https://gist.github.com/mehmooda/365da23726fcf52c46bccee8867ea0f2

I must not have noticed it when trying to simplify the code.

**Comment by KillingSpark** [comment]
I'll close this, I opened a new issue regarding the confusing interactions between `MessageParser::get` and variants. If the issue persists with the new version please feel free to reopen this or open a new issue :)
