### ISSUE TITLE
Support f64

### ISSUE THREAD

**Issue by MaxVerevkin** [KillingSpark/rustbus#86]
It seems that

- `f64` does not implement `Signature`, `Marshall` and `Unmarshall`.
- `Base::Double` holds a `u64`, not sure why?

**Comment by KillingSpark** [comment]
Why I didn't do the impls for f64/f32: Dunno I don't see a good reason not to do them

Why Double holds a u64:

The spec says that this type holds an u64 that represents an ieee754 double precision floating-point number (which is how rust represents f64). I would guess I wanted to ensure maximum interoperability and wasn't confident that it's fine to represent it as a f64. Ultimately it's just a to_/from_bits away.

**Comment by KillingSpark** [comment]
Hi @MaxVerevkin just wanted to let you know I saw your PRs. I'm afraid I'll have to postpone reviewing them until the weekend, but I'll get to it
