### ISSUE TITLE
[question] Why `Unmarshal` is generic ower two lifetimes?

### ISSUE THREAD

**Issue by MaxVerevkin** [KillingSpark/rustbus#95]
I couldn't find an example where the second lifetime makes a difference and is not ignored or assumed to be the same thing as the first lifetime. Don't both lifetimes usually just point to the lifetime of the associated `MarshalledMessage`? Plus `UnixFd` is cheaply cloneable.

**Comment by KillingSpark** [comment]
I think in practice this never really matters but technically you could construct something with the `yoke` crate to pass the unmarshalled message around together with the buffer holding the data but dropping the slice of unixfds after unmarshalling. To do this the two lifetimes need to be separated to ensure that the output only depends on the buffers lifetime and not on the fdunix's lifetime. Maybe that's wrong though?

**Comment by MaxVerevkin** [comment]
> pass the unmarshalled message around together with the buffer holding the data but dropping the slice of unixfds after unmarshalling

Thanks, that makes sense!
